version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: books-management
    ports:
      - '5432:5432'
    networks:
      - backend-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: admin
      DB_PASSWORD: password
      DB_DATABASE: books-management
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
